/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.uber.analytics.events;
@org.apache.avro.specific.AvroGenerated
public enum DriverEventType implements org.apache.avro.generic.GenericEnumSymbol<DriverEventType> {
  DRIVER_ONLINE, DRIVER_OFFLINE, LOCATION_UPDATE, STATUS_CHANGE, RIDE_ACCEPTED, RIDE_DECLINED, ARRIVED_AT_PICKUP, STARTED_TRIP, COMPLETED_TRIP  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"DriverEventType\",\"namespace\":\"com.uber.analytics.events\",\"symbols\":[\"DRIVER_ONLINE\",\"DRIVER_OFFLINE\",\"LOCATION_UPDATE\",\"STATUS_CHANGE\",\"RIDE_ACCEPTED\",\"RIDE_DECLINED\",\"ARRIVED_AT_PICKUP\",\"STARTED_TRIP\",\"COMPLETED_TRIP\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
