/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.uber.analytics.events;
@org.apache.avro.specific.AvroGenerated
public enum DriverStatus implements org.apache.avro.generic.GenericEnumSymbol<DriverStatus> {
  AVAILABLE, BUSY, OFFLINE, EN_ROUTE_TO_PICKUP, ARRIVED_AT_PICKUP, ON_TRIP  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"DriverStatus\",\"namespace\":\"com.uber.analytics.events\",\"symbols\":[\"AVAILABLE\",\"BUSY\",\"OFFLINE\",\"EN_ROUTE_TO_PICKUP\",\"ARRIVED_AT_PICKUP\",\"ON_TRIP\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
