/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.uber.analytics.events;
@org.apache.avro.specific.AvroGenerated
public enum OrderEventType implements org.apache.avro.generic.GenericEnumSymbol<OrderEventType> {
  ORDER_PLACED, ORDER_CONFIRMED, ORDER_PREPARING, ORDER_READY, ORDER_PICKED_UP, ORDER_DELIVERED, ORDER_CANCELLED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"OrderEventType\",\"namespace\":\"com.uber.analytics.events\",\"symbols\":[\"ORDER_PLACED\",\"ORDER_CONFIRMED\",\"ORDER_PREPARING\",\"ORDER_READY\",\"ORDER_PICKED_UP\",\"ORDER_DELIVERED\",\"ORDER_CANCELLED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
