/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.uber.analytics.events;
@org.apache.avro.specific.AvroGenerated
public enum PaymentMethod implements org.apache.avro.generic.GenericEnumSymbol<PaymentMethod> {
  CREDIT_CARD, DEBIT_CARD, DIGITAL_WALLET, CASH_ON_DELIVERY  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PaymentMethod\",\"namespace\":\"com.uber.analytics.events\",\"symbols\":[\"CREDIT_CARD\",\"DEBIT_CARD\",\"DIGITAL_WALLET\",\"CASH_ON_DELIVERY\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
