/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.uber.analytics.events;
@org.apache.avro.specific.AvroGenerated
public enum RideEventType implements org.apache.avro.generic.GenericEnumSymbol<RideEventType> {
  RIDE_REQUESTED, DRIVER_ASSIGNED, DRIVER_ARRIVED, RIDE_STARTED, RIDE_COMPLETED, RIDE_CANCELLED, PAYMENT_PROCESSED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"RideEventType\",\"namespace\":\"com.uber.analytics.events\",\"symbols\":[\"RIDE_REQUESTED\",\"DRIVER_ASSIGNED\",\"DRIVER_ARRIVED\",\"RIDE_STARTED\",\"RIDE_COMPLETED\",\"RIDE_CANCELLED\",\"PAYMENT_PROCESSED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
