/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.uber.analytics.events;
@org.apache.avro.specific.AvroGenerated
public enum RideType implements org.apache.avro.generic.GenericEnumSymbol<RideType> {
  UBER_X, UBER_XL, UBER_BLACK, UBER_POOL, UBER_EATS  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"RideType\",\"namespace\":\"com.uber.analytics.events\",\"symbols\":[\"UBER_X\",\"UBER_XL\",\"UBER_BLACK\",\"UBER_POOL\",\"UBER_EATS\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
