/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.uber.analytics.events;
@org.apache.avro.specific.AvroGenerated
public enum VehicleType implements org.apache.avro.generic.GenericEnumSymbol<VehicleType> {
  SEDAN, SUV, LUXURY, MOTORCYCLE, BICYCLE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"VehicleType\",\"namespace\":\"com.uber.analytics.events\",\"symbols\":[\"SEDAN\",\"SUV\",\"LUXURY\",\"MOTORCYCLE\",\"BICYCLE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
